### Read all texts with File variable

@baseUrl = http://localhost:3000

GET {{baseUrl}}/texts

### Create a text

POST {{baseUrl}}/texts
Content-Type: application/json

{
    "content" : "hello world",
    "level" : "easy"
}

### Update the text identified by 1
PUT {{baseUrl}}/texts/8af49519-e398-4e97-b80e-c33c939d86f3
Content-Type: application/json

{
    "content" : "coucou le monde",
    "level" : "easy"
}